CHAMPIONSHIPS = {
    'Alabama': 16,
    'Arkansas': 1,
    'Army': 3,
    'Auburn': 2,
    'BYU': 1,
    'California': 3,
    'Clemson': 3,
    'Colorado': 1,
    'Florida': 3,
    'Florida State': 3,
    'Georgia': 3,
    'Georgia Tech': 3,
    'Illinois': 3,
    'Iowa': 1,
    'LSU': 5,
    'Maryland': 1,
    'Miami': 5,
    'Michigan': 10,
    'Michigan State': 3,
    'Minnesota': 6,
    'Nebraska': 5,
    'Notre Dame': 13,
    'Ohio State': 9,
    'Oklahoma': 7,
    'Ole Miss': 1,
    'Penn State': 4,
    'Pittsburgh': 5,
    'Rutgers': 1,
    'Stanford': 1,
    'Syracuse': 1,
    'TCU': 1,
    'Tennessee': 2,
    'Texas': 4,
    'Texas A&M': 2,
    'UCLA': 1,
    'USC': 9,
    'Washington': 1,
}
