# Derived from records.json by selecting the best conference win pct per year.
# Ties count as co-championships; independent teams are excluded.
CONFERENCE_CHAMPIONSHIPS = {
    'Air Force': 3,
    'Alabama': 37,
    'App State': 19,
    'Arizona': 7,
    'Arizona State': 22,
    'Arkansas': 14,
    'Arkansas State': 10,
    'Army': 1,
    'Auburn': 11,
    'BYU': 23,
    'Ball State': 7,
    'Baylor': 8,
    'Boise State': 18,
    'Boston College': 1,
    'Bowling Green': 9,
    'Buffalo': 1,
    'California': 14,
    'Central Michigan': 7,
    'Cincinnati': 10,
    'Clemson': 26,
    'Coastal Carolina': 8,
    'Colorado': 22,
    'Colorado State': 13,
    'Delaware': 7,
    'Duke': 19,
    'East Carolina': 9,
    'Eastern Michigan': 1,
    'Florida': 11,
    'Florida Atlantic': 5,
    'Florida International': 1,
    'Florida State': 16,
    'Fresno State': 13,
    'Georgia': 16,
    'Georgia Southern': 5,
    'Georgia Tech': 12,
    "Hawai'i": 4,
    'Houston': 14,
    'Illinois': 16,
    'Indiana': 3,
    'Iowa': 10,
    'Iowa State': 3,
    'Jacksonville State': 19,
    'James Madison': 12,
    'Kansas': 8,
    'Kansas State': 4,
    'Kennesaw State': 6,
    'Kent State': 1,
    'Kentucky': 2,
    'LSU': 13,
    'Liberty': 10,
    'Louisiana': 7,
    'Louisiana Tech': 5,
    'Louisville': 8,
    'Marshall': 7,
    'Maryland': 12,
    'Massachusetts': 4,
    'Memphis': 4,
    'Miami': 9,
    'Miami (OH)': 11,
    'Michigan': 45,
    'Michigan State': 10,
    'Middle Tennessee': 2,
    'Minnesota': 18,
    'Mississippi State': 1,
    'Missouri': 11,
    'Missouri State': 18,
    'NC State': 7,
    'Navy': 1,
    'Nebraska': 43,
    'Nevada': 8,
    'New Mexico': 3,
    'New Mexico State': 4,
    'North Carolina': 10,
    'North Texas': 13,
    'Northern Illinois': 8,
    'Northwestern': 7,
    'Ohio': 4,
    'Ohio State': 41,
    'Oklahoma': 49,
    'Oklahoma State': 17,
    'Old Dominion': 4,
    'Ole Miss': 5,
    'Oregon': 13,
    'Oregon State': 7,
    'Penn State': 3,
    'Pittsburgh': 3,
    'Purdue': 7,
    'Rice': 8,
    'Rutgers': 1,
    'SMU': 13,
    'Sam Houston': 17,
    'San Diego State': 10,
    'San José State': 11,
    'South Carolina': 3,
    'Southern Miss': 3,
    'Stanford': 15,
    'Syracuse': 6,
    'TCU': 19,
    'Temple': 1,
    'Tennessee': 12,
    'Texas': 30,
    'Texas A&M': 18,
    'Texas State': 3,
    'Texas Tech': 19,
    'Toledo': 13,
    'Troy': 8,
    'Tulane': 10,
    'Tulsa': 30,
    'UAB': 2,
    'UCF': 7,
    'UCLA': 17,
    'UConn': 2,
    'UL Monroe': 1,
    'UNLV': 2,
    'USC': 41,
    'UTEP': 2,
    'UTSA': 3,
    'Utah': 27,
    'Utah State': 13,
    'Vanderbilt': 2,
    'Virginia': 3,
    'Virginia Tech': 16,
    'Wake Forest': 2,
    'Washington': 18,
    'Washington State': 4,
    'West Virginia': 19,
    'Western Kentucky': 6,
    'Western Michigan': 4,
    'Wisconsin': 14,
    'Wyoming': 15,
}
