HEISMANS = {
    # Keys are canonical school names; values are total Heisman winners.
    "Alabama": 4,
    "Army": 3,
    "Auburn": 3,
    "BYU": 1,
    "Baylor": 1,
    "Boston College": 1,
    "Colorado": 2,
    "Florida": 3,
    "Florida State": 3,
    "Georgia": 2,
    "Houston": 1,
    "Indiana": 1,
    "Iowa": 1,
    "LSU": 3,
    "Louisville": 1,
    "Miami": 2,
    "Michigan": 3,
    "Minnesota": 1,
    "Navy": 2,
    "Nebraska": 3,
    "Notre Dame": 7,
    "Ohio State": 7,
    "Oklahoma": 7,
    "Oklahoma State": 1,
    "Oregon": 1,
    "Oregon State": 1,
    "Penn State": 1,
    "Pittsburgh": 1,
    "SMU": 1,
    "South Carolina": 1,
    "Stanford": 1,
    "Syracuse": 1,
    "TCU": 1,
    "Texas": 2,
    "Texas A&M": 2,
    "UCLA": 1,
    "USC": 8,
    "Wisconsin": 2,
}
