MASCOTS = {
    # Keys are canonical school names; values include mascot name and type.
    'Air Force': {"mascot": 'Falcons', "type": 'bird'},
    'Akron': {"mascot": 'Zips', "type": 'other'},
    'Alabama': {"mascot": 'Crimson Tide', "type": 'other'},
    'App State': {"mascot": 'Mountaineers', "type": 'human'},
    'Arizona': {"mascot": 'Wildcats', "type": 'cat'},
    'Arizona State': {"mascot": 'Sun Devils', "type": 'mythic'},
    'Arkansas': {"mascot": 'Razorbacks', "type": 'other'},
    'Arkansas State': {"mascot": 'Red Wolves', "type": 'dog'},
    'Army': {"mascot": 'Black Knights', "type": 'human'},
    'Auburn': {"mascot": 'Tigers', "type": 'cat'},
    'Ball State': {"mascot": 'Cardinals', "type": 'bird'},
    'Baylor': {"mascot": 'Bears', "type": 'bear'},
    'Boise State': {"mascot": 'Broncos', "type": 'horse'},
    'Boston College': {"mascot": 'Eagles', "type": 'bird'},
    'Bowling Green': {"mascot": 'Falcons', "type": 'bird'},
    'Buffalo': {"mascot": 'Bulls', "type": 'bovine'},
    'BYU': {"mascot": 'Cougars', "type": 'cat'},
    'California': {"mascot": 'Golden Bears', "type": 'bear'},
    'Central Michigan': {"mascot": 'Chippewas', "type": 'human'},
    'Charlotte': {"mascot": '49ers', "type": 'human'},
    'Cincinnati': {"mascot": 'Bearcats', "type": 'other'},
    'Clemson': {"mascot": 'Tigers', "type": 'cat'},
    'Coastal Carolina': {"mascot": 'Chanticleers', "type": 'bird'},
    'Colorado': {"mascot": 'Buffaloes', "type": 'bovine'},
    'Colorado State': {"mascot": 'Rams', "type": 'other'},
    'Delaware': {"mascot": 'Blue Hens', "type": 'bird'},
    'Duke': {"mascot": 'Blue Devils', "type": 'mythic'},
    'East Carolina': {"mascot": 'Pirates', "type": 'human'},
    'Eastern Michigan': {"mascot": 'Eagles', "type": 'bird'},
    'Florida': {"mascot": 'Gators', "type": 'reptile'},
    'Florida Atlantic': {"mascot": 'Owls', "type": 'bird'},
    'Florida International': {"mascot": 'Panthers', "type": 'cat'},
    'Florida State': {"mascot": 'Seminoles', "type": 'human'},
    'Fresno State': {"mascot": 'Bulldogs', "type": 'dog'},
    'Georgia': {"mascot": 'Bulldogs', "type": 'dog'},
    'Georgia Southern': {"mascot": 'Eagles', "type": 'bird'},
    'Georgia State': {"mascot": 'Panthers', "type": 'cat'},
    'Georgia Tech': {"mascot": 'Yellow Jackets', "type": 'insect'},
    "Hawai'i": {"mascot": 'Rainbow Warriors', "type": 'human'},
    'Houston': {"mascot": 'Cougars', "type": 'cat'},
    'Illinois': {"mascot": 'Fighting Illini', "type": 'human'},
    'Indiana': {"mascot": 'Hoosiers', "type": 'human'},
    'Iowa': {"mascot": 'Hawkeyes', "type": 'human'},
    'Iowa State': {"mascot": 'Cyclones', "type": 'weather'},
    'Jacksonville State': {"mascot": 'Gamecocks', "type": 'bird'},
    'James Madison': {"mascot": 'Dukes', "type": 'human'},
    'Kansas': {"mascot": 'Jayhawks', "type": 'bird'},
    'Kansas State': {"mascot": 'Wildcats', "type": 'cat'},
    'Kennesaw State': {"mascot": 'Owls', "type": 'bird'},
    'Kent State': {"mascot": 'Golden Flashes', "type": 'weather'},
    'Kentucky': {"mascot": 'Wildcats', "type": 'cat'},
    'Liberty': {"mascot": 'Flames', "type": 'object'},
    'Louisiana': {"mascot": "Ragin' Cajuns", "type": 'human'},
    'Louisiana Tech': {"mascot": 'Bulldogs', "type": 'dog'},
    'Louisville': {"mascot": 'Cardinals', "type": 'bird'},
    'LSU': {"mascot": 'Tigers', "type": 'cat'},
    'Marshall': {"mascot": 'Thundering Herd', "type": 'bovine'},
    'Maryland': {"mascot": 'Terrapins', "type": 'reptile'},
    'Massachusetts': {"mascot": 'Minutemen', "type": 'human'},
    'Memphis': {"mascot": 'Tigers', "type": 'cat'},
    'Miami': {"mascot": 'Hurricanes', "type": 'weather'},
    'Miami (OH)': {"mascot": 'RedHawks', "type": 'bird'},
    'Michigan': {"mascot": 'Wolverines', "type": 'other'},
    'Michigan State': {"mascot": 'Spartans', "type": 'human'},
    'Middle Tennessee': {"mascot": 'Blue Raiders', "type": 'human'},
    'Minnesota': {"mascot": 'Golden Gophers', "type": 'other'},
    'Mississippi State': {"mascot": 'Bulldogs', "type": 'dog'},
    'Missouri': {"mascot": 'Tigers', "type": 'cat'},
    'Missouri State': {"mascot": 'Bears', "type": 'bear'},
    'Navy': {"mascot": 'Midshipmen', "type": 'human'},
    'NC State': {"mascot": 'Wolfpack', "type": 'dog'},
    'Nebraska': {"mascot": 'Cornhuskers', "type": 'human'},
    'Nevada': {"mascot": 'Wolf Pack', "type": 'dog'},
    'New Mexico': {"mascot": 'Lobos', "type": 'dog'},
    'New Mexico State': {"mascot": 'Aggies', "type": 'human'},
    'North Carolina': {"mascot": 'Tar Heels', "type": 'human'},
    'North Texas': {"mascot": 'Mean Green', "type": 'other'},
    'Northern Illinois': {"mascot": 'Huskies', "type": 'dog'},
    'Northwestern': {"mascot": 'Wildcats', "type": 'cat'},
    'Notre Dame': {"mascot": 'Fighting Irish', "type": 'human'},
    'Ohio': {"mascot": 'Bobcats', "type": 'cat'},
    'Ohio State': {"mascot": 'Buckeyes', "type": 'plant'},
    'Oklahoma': {"mascot": 'Sooners', "type": 'human'},
    'Oklahoma State': {"mascot": 'Cowboys', "type": 'human'},
    'Old Dominion': {"mascot": 'Monarchs', "type": 'human'},
    'Ole Miss': {"mascot": 'Rebels', "type": 'human'},
    'Oregon': {"mascot": 'Ducks', "type": 'bird'},
    'Oregon State': {"mascot": 'Beavers', "type": 'other'},
    'Penn State': {"mascot": 'Nittany Lions', "type": 'cat'},
    'Pittsburgh': {"mascot": 'Panthers', "type": 'cat'},
    'Purdue': {"mascot": 'Boilermakers', "type": 'human'},
    'Rice': {"mascot": 'Owls', "type": 'bird'},
    'Rutgers': {"mascot": 'Scarlet Knights', "type": 'human'},
    'Sam Houston': {"mascot": 'Bearkats', "type": 'other'},
    'San Diego State': {"mascot": 'Aztecs', "type": 'human'},
    'San José State': {"mascot": 'Spartans', "type": 'human'},
    'SMU': {"mascot": 'Mustangs', "type": 'horse'},
    'South Alabama': {"mascot": 'Jaguars', "type": 'cat'},
    'South Carolina': {"mascot": 'Gamecocks', "type": 'bird'},
    'South Florida': {"mascot": 'Bulls', "type": 'bovine'},
    'Southern Miss': {"mascot": 'Golden Eagles', "type": 'bird'},
    'Stanford': {"mascot": 'Cardinal', "type": 'bird'},
    'Syracuse': {"mascot": 'Orange', "type": 'plant'},
    'TCU': {"mascot": 'Horned Frogs', "type": 'reptile'},
    'Temple': {"mascot": 'Owls', "type": 'bird'},
    'Tennessee': {"mascot": 'Volunteers', "type": 'human'},
    'Texas': {"mascot": 'Longhorns', "type": 'bovine'},
    'Texas A&M': {"mascot": 'Aggies', "type": 'human'},
    'Texas State': {"mascot": 'Bobcats', "type": 'cat'},
    'Texas Tech': {"mascot": 'Red Raiders', "type": 'human'},
    'Toledo': {"mascot": 'Rockets', "type": 'object'},
    'Troy': {"mascot": 'Trojans', "type": 'human'},
    'Tulane': {"mascot": 'Green Wave', "type": 'weather'},
    'Tulsa': {"mascot": 'Golden Hurricane', "type": 'weather'},
    'UAB': {"mascot": 'Blazers', "type": 'object'},
    'UCF': {"mascot": 'Knights', "type": 'human'},
    'UCLA': {"mascot": 'Bruins', "type": 'bear'},
    'UConn': {"mascot": 'Huskies', "type": 'dog'},
    'UL Monroe': {"mascot": 'Warhawks', "type": 'bird'},
    'UNLV': {"mascot": 'Rebels', "type": 'human'},
    'USC': {"mascot": 'Trojans', "type": 'human'},
    'Utah': {"mascot": 'Utes', "type": 'human'},
    'Utah State': {"mascot": 'Aggies', "type": 'bovine'},
    'UTEP': {"mascot": 'Miners', "type": 'human'},
    'UTSA': {"mascot": 'Roadrunners', "type": 'bird'},
    'Vanderbilt': {"mascot": 'Commodores', "type": 'human'},
    'Virginia': {"mascot": 'Cavaliers', "type": 'human'},
    'Virginia Tech': {"mascot": 'Hokies', "type": 'bird'},
    'Wake Forest': {"mascot": 'Demon Deacons', "type": 'mythic'},
    'Washington': {"mascot": 'Huskies', "type": 'dog'},
    'Washington State': {"mascot": 'Cougars', "type": 'cat'},
    'West Virginia': {"mascot": 'Mountaineers', "type": 'human'},
    'Western Kentucky': {"mascot": 'Hilltoppers', "type": 'human'},
    'Western Michigan': {"mascot": 'Broncos', "type": 'horse'},
    'Wisconsin': {"mascot": 'Badgers', "type": 'other'},
    'Wyoming': {"mascot": 'Cowboys', "type": 'human'},
}
